-- Optional: run in Supabase SQL editor so arena reactions + global chat broadcast to all signed-in clients.
-- Without this table, reactions still post to the local "Tape" feed only.
--
-- REQUIRED for live cross-player chat:
--   Dashboard → Database → Publications → supabase_realtime → enable `arena_ping` (or run:
--   alter publication supabase_realtime add table public.arena_ping;

create table if not exists public.arena_ping (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  username text,
  payload text not null default '',
  kind text not null default 'react',
  created_at timestamptz not null default now()
);

create index if not exists arena_ping_created_idx on public.arena_ping (created_at desc);

alter table public.arena_ping enable row level security;

drop policy if exists "arena_ping_select_all" on public.arena_ping;
create policy "arena_ping_select_all" on public.arena_ping for select using (true);

drop policy if exists "arena_ping_insert_own" on public.arena_ping;
create policy "arena_ping_insert_own" on public.arena_ping for insert with check (auth.uid() = user_id);

-- Realtime (required for live chat/reactions across browsers):
-- In Supabase Dashboard → Database → Replication, add `arena_ping` to the `supabase_realtime` publication,
-- or run: alter publication supabase_realtime add table public.arena_ping;

-- PostgREST must be able to read/write rows; the table lives in schema **public** as **arena_ping**
-- (not public_arena_ping). If the dashboard shows "could not find table …", re-run this file.
grant select, insert on public.arena_ping to authenticated;
grant select on public.arena_ping to anon;

-- Optional but recommended: clients call this RPC so chat still works if table grants were misconfigured.
-- Inserts as the signed-in user (auth.uid()); ignores client-supplied user_id.
create or replace function public.mm_arena_ping_send(p_username text, p_payload text, p_kind text default 'react')
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    raise exception 'not_authenticated';
  end if;
  insert into public.arena_ping (user_id, username, payload, kind)
  values (
    v_uid,
    left(coalesce(nullif(trim(p_username), ''), 'player'), 120),
    left(coalesce(p_payload, ''), 500),
    left(coalesce(nullif(trim(p_kind), ''), 'react'), 32)
  );
end;
$$;

revoke all on function public.mm_arena_ping_send(text, text, text) from public;
grant execute on function public.mm_arena_ping_send(text, text, text) to authenticated;
