-- Player-to-player interactions: DMs, shared-wallet gifts, thread fetch, inbox list.
-- Run in Supabase SQL after: social_core_schema.sql, shared_trade_rpc.sql
--
-- Clients use:
--   mm_send_direct_message(p_to_username, p_body)
--   mm_transfer_shared_cash(p_to_username, p_amount)
--   mm_fetch_peer_thread(p_peer_username, p_limit)
--   mm_list_inbox_peers(p_limit)

-- ----------------------------------------------------------------------------- messages
create table if not exists public.mm_player_direct_message (
  id bigint generated by default as identity primary key,
  from_user uuid not null references auth.users (id) on delete cascade,
  to_user uuid not null references auth.users (id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now()
);

create index if not exists mm_pdm_pair_created_idx
  on public.mm_player_direct_message (from_user, to_user, created_at asc);
create index if not exists mm_pdm_pair_rev_created_idx
  on public.mm_player_direct_message (to_user, from_user, created_at asc);

alter table public.mm_player_direct_message enable row level security;

drop policy if exists "mm_pdm_select_parties" on public.mm_player_direct_message;
create policy "mm_pdm_select_parties"
  on public.mm_player_direct_message for select
  using (auth.uid() = from_user or auth.uid() = to_user);

drop policy if exists "mm_pdm_insert_sender" on public.mm_player_direct_message;
create policy "mm_pdm_insert_sender"
  on public.mm_player_direct_message for insert
  with check (auth.uid() = from_user);

grant select, insert on public.mm_player_direct_message to authenticated;

-- ----------------------------------------------------------------------------- transfer log (for both players to read)
create table if not exists public.mm_player_wallet_transfer (
  id bigint generated by default as identity primary key,
  from_user uuid not null references auth.users (id) on delete cascade,
  to_user uuid not null references auth.users (id) on delete cascade,
  amount numeric not null,
  created_at timestamptz not null default now()
);

create index if not exists mm_pwt_pair_created_idx
  on public.mm_player_wallet_transfer (from_user, to_user, created_at asc);

alter table public.mm_player_wallet_transfer enable row level security;

drop policy if exists "mm_pwt_select_parties" on public.mm_player_wallet_transfer;
create policy "mm_pwt_select_parties"
  on public.mm_player_wallet_transfer for select
  using (auth.uid() = from_user or auth.uid() = to_user);

grant select on public.mm_player_wallet_transfer to authenticated;

-- ----------------------------------------------------------------------------- mm_send_direct_message
create or replace function public.mm_send_direct_message(p_to_username text, p_body text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_from uuid := auth.uid();
  v_to uuid;
  v_body text := left(trim(coalesce(p_body, '')), 800);
begin
  if v_from is null then
    return jsonb_build_object('ok', false, 'error', 'not_authenticated');
  end if;
  if v_body = '' then
    return jsonb_build_object('ok', false, 'error', 'empty_body');
  end if;
  select p.id into v_to
  from public.profiles p
  where lower(p.username) = lower(trim(p_to_username))
  limit 1;
  if v_to is null then
    return jsonb_build_object('ok', false, 'error', 'recipient_not_found');
  end if;
  if v_to = v_from then
    return jsonb_build_object('ok', false, 'error', 'cannot_message_self');
  end if;
  insert into public.mm_player_direct_message (from_user, to_user, body)
  values (v_from, v_to, v_body);
  return jsonb_build_object('ok', true);
end;
$$;

revoke all on function public.mm_send_direct_message(text, text) from public;
grant execute on function public.mm_send_direct_message(text, text) to authenticated;

-- ----------------------------------------------------------------------------- mm_transfer_shared_cash (+ log row)
create or replace function public.mm_transfer_shared_cash(p_to_username text, p_amount numeric)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_from uuid := auth.uid();
  v_to uuid;
  v_amt numeric := round(coalesce(p_amount, 0)::numeric, 2);
  v_scash numeric;
  v_rcash numeric;
begin
  if v_from is null then
    return jsonb_build_object('ok', false, 'error', 'not_authenticated');
  end if;
  if v_amt < 1 then
    return jsonb_build_object('ok', false, 'error', 'amount_too_small');
  end if;
  if v_amt > 1e15::numeric then
    return jsonb_build_object('ok', false, 'error', 'amount_too_large');
  end if;
  select p.id into v_to
  from public.profiles p
  where lower(p.username) = lower(trim(p_to_username))
  limit 1;
  if v_to is null then
    return jsonb_build_object('ok', false, 'error', 'recipient_not_found');
  end if;
  if v_to = v_from then
    return jsonb_build_object('ok', false, 'error', 'cannot_transfer_self');
  end if;

  insert into public.player_wallet (user_id, cash) values (v_from, 500)
  on conflict (user_id) do nothing;
  insert into public.player_wallet (user_id, cash) values (v_to, 500)
  on conflict (user_id) do nothing;

  if v_from < v_to then
    perform 1 from public.player_wallet where user_id = v_from for update;
    perform 1 from public.player_wallet where user_id = v_to for update;
  else
    perform 1 from public.player_wallet where user_id = v_to for update;
    perform 1 from public.player_wallet where user_id = v_from for update;
  end if;

  v_scash := (select pw.cash from public.player_wallet pw where pw.user_id = v_from limit 1);
  if v_scash < v_amt then
    return jsonb_build_object('ok', false, 'error', 'insufficient_cash');
  end if;
  v_rcash := (select pw.cash from public.player_wallet pw where pw.user_id = v_to limit 1);

  update public.player_wallet set cash = v_scash - v_amt, updated_at = now() where user_id = v_from;
  update public.player_wallet set cash = v_rcash + v_amt, updated_at = now() where user_id = v_to;

  insert into public.mm_player_wallet_transfer (from_user, to_user, amount)
  values (v_from, v_to, v_amt);

  return jsonb_build_object(
    'ok', true,
    'your_cash', v_scash - v_amt,
    'peer_cash', v_rcash + v_amt
  );
end;
$$;

revoke all on function public.mm_transfer_shared_cash(text, numeric) from public;
grant execute on function public.mm_transfer_shared_cash(text, numeric) to authenticated;

-- ----------------------------------------------------------------------------- mm_fetch_peer_thread (messages + payments, chronological)
create or replace function public.mm_fetch_peer_thread(p_peer_username text, p_limit int default 120)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_me uuid := auth.uid();
  v_peer uuid;
  lim int := greatest(1, least(500, coalesce(p_limit, 120)));
  arr jsonb := '[]'::jsonb;
  r record;
begin
  if v_me is null then
    return jsonb_build_object('ok', false, 'error', 'not_authenticated');
  end if;
  select p.id into v_peer
  from public.profiles p
  where lower(p.username) = lower(trim(p_peer_username))
  limit 1;
  if v_peer is null then
    return jsonb_build_object('ok', false, 'error', 'recipient_not_found');
  end if;
  if v_peer = v_me then
    return jsonb_build_object('ok', false, 'error', 'cannot_thread_self');
  end if;

  for r in
    select * from (
      select m.id, 'msg'::text as kind, m.created_at as at, (m.from_user = v_me) as outgoing, m.body::text as txt
      from public.mm_player_direct_message m
      where (m.from_user = v_me and m.to_user = v_peer)
         or (m.from_user = v_peer and m.to_user = v_me)
      union all
      select t.id, 'pay'::text as kind, t.created_at as at, (t.from_user = v_me) as outgoing,
        trim(to_char(t.amount, 'FM9999999999999990.00')) as txt
      from public.mm_player_wallet_transfer t
      where (t.from_user = v_me and t.to_user = v_peer)
         or (t.from_user = v_peer and t.to_user = v_me)
    ) u
    order by at asc
    limit lim
  loop
    arr := arr || jsonb_build_array(jsonb_build_object(
      'id', r.id,
      'kind', r.kind,
      'at', r.at,
      'out', r.outgoing,
      'text', case when r.kind = 'pay' then '$' || r.txt else r.txt end
    ));
  end loop;

  return jsonb_build_object('ok', true, 'items', arr);
end;
$$;

revoke all on function public.mm_fetch_peer_thread(text, int) from public;
grant execute on function public.mm_fetch_peer_thread(text, int) to authenticated;

-- ----------------------------------------------------------------------------- mm_list_inbox_peers (for "your" card — jump to chats)
create or replace function public.mm_list_inbox_peers(p_limit int default 40)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_me uuid := auth.uid();
  lim int := greatest(1, least(100, coalesce(p_limit, 40)));
  arr jsonb := '[]'::jsonb;
  r record;
begin
  if v_me is null then
    return jsonb_build_object('ok', false, 'error', 'not_authenticated');
  end if;

  for r in
    with ev as (
      select case when from_user = v_me then to_user else from_user end as peer_id, created_at
      from public.mm_player_direct_message
      where from_user = v_me or to_user = v_me
      union all
      select case when from_user = v_me then to_user else from_user end, created_at
      from public.mm_player_wallet_transfer
      where from_user = v_me or to_user = v_me
    ),
    agg as (
      select peer_id, max(created_at) as last_at
      from ev
      where peer_id is distinct from v_me
      group by peer_id
    )
    select pr.username as username, a.last_at
    from agg a
    join public.profiles pr on pr.id = a.peer_id
    order by a.last_at desc
    limit lim
  loop
    arr := arr || jsonb_build_array(jsonb_build_object(
      'username', r.username,
      'last_at', r.last_at
    ));
  end loop;

  return jsonb_build_object('ok', true, 'peers', arr);
end;
$$;

revoke all on function public.mm_list_inbox_peers(int) from public;
grant execute on function public.mm_list_inbox_peers(int) to authenticated;
