-- =============================================================================
-- SHARED WORLD MARKET — normalized tables + fan-out from shared_market_snapshot
-- =============================================================================
-- Leaderboard / live players: if the game hub shows empty rankings, run
-- `leaderboard_public_rpc.sql` in the SQL editor (RPC mm_public_leaderboard).
-- Authoritative tape math should run only in Supabase Edge (`shared-market-tick`).
-- Browsers subscribe to `shared_market_snapshot` (existing) and/or these tables.
--
-- MANUAL DEPLOY:
--   1) Run shared_market_snapshot.sql (if not already).
--   2) Run this file in Supabase SQL editor.
--   3) Deploy Edge Function `shared-market-tick` with secrets SUPABASE_SERVICE_ROLE_KEY,
--      SUPABASE_URL, optional MM_CRON_SECRET.
--   4) Schedule: Supabase Dashboard → Edge Functions → Cron, every 3s (or match MARKET_TICK_MS).
--   5) Enable Realtime on tables you want live UI for (shared_stocks, shared_activity_feed, online_presence).
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1) shared_market_state — one row mirror of global clock / mood (denormalized)
-- -----------------------------------------------------------------------------
create table if not exists public.shared_market_state (
  id int primary key default 1,
  current_tick bigint not null default 0,
  sim_gen bigint not null default 0,
  market_mood text,
  day_count int not null default 1,
  sim_hour int not null default 0,
  last_updated_at timestamptz not null default now(),
  authority text not null default 'client',
  meta jsonb not null default '{}'::jsonb
);

insert into public.shared_market_state (id) values (1) on conflict (id) do nothing;

alter table public.shared_market_state enable row level security;
drop policy if exists "shared_market_state_select" on public.shared_market_state;
create policy "shared_market_state_select" on public.shared_market_state for select using (true);

-- -----------------------------------------------------------------------------
-- 2) shared_stocks — one row per symbol (fed by trigger from snapshot payload)
-- -----------------------------------------------------------------------------
create table if not exists public.shared_stocks (
  symbol text primary key,
  name text,
  sector text,
  price numeric not null default 0,
  previous_price numeric,
  fair_value numeric,
  day_high numeric,
  day_low numeric,
  last_delta numeric,
  liquidity numeric,
  participants numeric,
  updated_at timestamptz not null default now(),
  wire jsonb not null default '{}'::jsonb
);

create index if not exists shared_stocks_updated_idx on public.shared_stocks (updated_at desc);

alter table public.shared_stocks enable row level security;
drop policy if exists "shared_stocks_select" on public.shared_stocks;
create policy "shared_stocks_select" on public.shared_stocks for select using (true);

-- -----------------------------------------------------------------------------
-- 3) shared_stock_history — optional tick log (keep small; prune by cron)
-- -----------------------------------------------------------------------------
create table if not exists public.shared_stock_history (
  id bigint generated by default as identity primary key,
  symbol text not null,
  tick bigint not null,
  sim_gen bigint not null,
  price numeric not null,
  created_at timestamptz not null default now()
);

create index if not exists shared_stock_history_sym_time on public.shared_stock_history (symbol, created_at desc);

alter table public.shared_stock_history enable row level security;
drop policy if exists "shared_stock_history_select" on public.shared_stock_history;
create policy "shared_stock_history_select" on public.shared_stock_history for select using (true);

-- -----------------------------------------------------------------------------
-- 4) shared_market_events — active + past global tape events
-- -----------------------------------------------------------------------------
create table if not exists public.shared_market_events (
  id bigint generated by default as identity primary key,
  event_type text not null default 'global',
  title text not null,
  description text,
  effect_json jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  ends_at timestamptz,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists shared_market_events_active_idx on public.shared_market_events (is_active, started_at desc);

alter table public.shared_market_events enable row level security;
drop policy if exists "shared_market_events_select" on public.shared_market_events;
create policy "shared_market_events_select" on public.shared_market_events for select using (true);

-- -----------------------------------------------------------------------------
-- 5) shared_activity_feed — public tape / notable actions (server or RPC insert)
-- -----------------------------------------------------------------------------
create table if not exists public.shared_activity_feed (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete set null,
  username text,
  activity_type text not null default 'info',
  text text not null,
  metadata_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists shared_activity_feed_time on public.shared_activity_feed (created_at desc);

alter table public.shared_activity_feed enable row level security;
drop policy if exists "shared_activity_feed_select" on public.shared_activity_feed;
create policy "shared_activity_feed_select" on public.shared_activity_feed for select using (true);
drop policy if exists "shared_activity_feed_insert_auth" on public.shared_activity_feed;
create policy "shared_activity_feed_insert_auth" on public.shared_activity_feed
  for insert to authenticated with check (auth.uid() = user_id or user_id is null);

-- -----------------------------------------------------------------------------
-- 6) online_presence — heartbeat (client upserts own row)
-- -----------------------------------------------------------------------------
create table if not exists public.online_presence (
  user_id uuid primary key references auth.users (id) on delete cascade,
  username text,
  display_name text,
  last_seen timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists online_presence_seen_idx on public.online_presence (last_seen desc);

alter table public.online_presence enable row level security;
drop policy if exists "online_presence_select" on public.online_presence;
create policy "online_presence_select" on public.online_presence for select using (true);
drop policy if exists "online_presence_insert_own" on public.online_presence;
drop policy if exists "online_presence_update_own" on public.online_presence;
create policy "online_presence_insert_own" on public.online_presence
  for insert to authenticated with check (auth.uid() = user_id);
create policy "online_presence_update_own" on public.online_presence
  for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- -----------------------------------------------------------------------------
-- 7) Fan-out trigger: snapshot JSON → shared_market_state + shared_stocks + event row
-- -----------------------------------------------------------------------------
create or replace function public.mm_fanout_shared_market_snapshot()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  p jsonb := coalesce(NEW.payload, '{}'::jsonb);
  stk jsonb;
  sym text;
begin
  insert into public.shared_market_state (id, current_tick, sim_gen, market_mood, day_count, sim_hour, last_updated_at, meta)
  values (
    1,
    NEW.tick,
    NEW.sim_gen,
    coalesce(p->>'mood', 'Balanced'),
    coalesce((p->>'dayCount')::int, 1),
    coalesce((p->>'simHourOfDay')::int, 0),
    coalesce(NEW.updated_at, now()),
    jsonb_build_object('gen', p->'gen', 'v', p->'v')
  )
  on conflict (id) do update set
    current_tick = excluded.current_tick,
    sim_gen = excluded.sim_gen,
    market_mood = excluded.market_mood,
    day_count = excluded.day_count,
    sim_hour = excluded.sim_hour,
    last_updated_at = excluded.last_updated_at,
    meta = shared_market_state.meta || excluded.meta;

  if jsonb_typeof(p->'stocks') = 'array' then
    for stk in select * from jsonb_array_elements(p->'stocks') loop
      sym := upper(coalesce(stk->>'symbol', ''));
      continue when sym = '';
      insert into public.shared_stocks (symbol, name, sector, price, previous_price, fair_value, day_high, day_low, last_delta, liquidity, participants, updated_at, wire)
      values (
        sym,
        stk->>'name',
        stk->>'sector',
        coalesce((stk->>'price')::numeric, 0),
        coalesce((stk->>'price')::numeric, 0),
        nullif(stk->>'fairValue', '')::numeric,
        nullif(stk->>'dayHigh', '')::numeric,
        nullif(stk->>'dayLow', '')::numeric,
        nullif(stk->>'lastDelta', '')::numeric,
        nullif(stk->>'liquidity', '')::numeric,
        nullif(stk->>'participants', '')::numeric,
        coalesce(NEW.updated_at, now()),
        stk
      )
      on conflict (symbol) do update set
        name = excluded.name,
        sector = excluded.sector,
        previous_price = shared_stocks.price,
        price = excluded.price,
        fair_value = excluded.fair_value,
        day_high = excluded.day_high,
        day_low = excluded.day_low,
        last_delta = excluded.last_delta,
        liquidity = excluded.liquidity,
        participants = excluded.participants,
        updated_at = excluded.updated_at,
        wire = excluded.wire;
    end loop;
  end if;

  -- globalEvent lives in snapshot payload; avoid inserting a DB row on every tick here.

  return NEW;
end;
$$;

drop trigger if exists mm_trg_fanout_shared_snapshot on public.shared_market_snapshot;
create trigger mm_trg_fanout_shared_snapshot
  after insert or update on public.shared_market_snapshot
  for each row execute function public.mm_fanout_shared_market_snapshot();

-- -----------------------------------------------------------------------------
-- Optional: prune history (run occasionally via cron)
-- -----------------------------------------------------------------------------
-- delete from public.shared_stock_history where created_at < now() - interval '7 days';
